apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-recommender-deployment
  namespace: anime-system
  labels:
    app: anime-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime-recommender
  template:
    metadata:
      labels:
        app: anime-recommender
    spec:
      containers:
        - name: anime-recommender
          image: farhanrhine/anime-recommender-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anime-secrets
                  key: GROQ_API_KEY
            - name: HUGGINGFACEHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: anime-secrets
                  key: HUGGINGFACEHUB_API_TOKEN
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: anime-secrets
                  key: LANGCHAIN_API_KEY
            - name: LANGCHAIN_TRACING_V2
              valueFrom:
                secretKeyRef:
                  name: anime-secrets
                  key: LANGCHAIN_TRACING_V2
            - name: LANGCHAIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: anime-secrets
                  key: LANGCHAIN_ENDPOINT
            - name: LANGCHAIN_PROJECT
              valueFrom:
                secretKeyRef:
                  name: anime-secrets
                  key: LANGCHAIN_PROJECT
          volumeMounts:
            - name: chroma-storage
              mountPath: /app/chroma_db
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "3Gi"
      volumes:
        - name: chroma-storage
          persistentVolumeClaim:
            claimName: chroma-pvc
