apiVersion: v1
kind: PersistentVolume
metadata:
  name: anime-chroma-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: chroma-storage
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: ai-anime-chroma-disk
    fsType: ext4
