apiVersion: v1
kind: Service
metadata:
  name: anime-recommender-svc
  namespace: anime-system
  labels:
    app: anime-recommender
spec:
  selector:
    app: anime-recommender
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # external public port
      targetPort: 8000
